inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - vendor/ruby/**/*
    - node_modules/**/*
    - .licenses/**/*
    - db/migrate/*
Rails:
  Enabled: true
Rails/NotNullColumn:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - db/migrate/*
    - config/environments/*
    - lib/tasks/**/*
    - spec/**/*
Naming/VariableNumber:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - Gemfile
Lint/EmptyBlock:
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Exclude:
    - db/migrate/*
Metrics/AbcSize:
  Exclude:
    - db/migrate/*
